-- ============================================================
-- Airline Reservation System (AirBooking)
-- CSE 305 Term Project — Triggers & Stored Procedures
-- ============================================================
-- Execute AFTER 01_schema.sql and BEFORE 03_seed_sample_data.sql
-- ============================================================


-- ############################################################
-- PART A. TRIGGERS (Advanced Feature)
-- ############################################################

-- ============================================================
-- TRIGGER 1: Auto-generate physical seats on SEAT_CLASS INSERT
-- ============================================================
-- Business logic automation: when a SEAT_CLASS row is inserted,
-- automatically populate SEAT_INVENTORY with physical seats
-- based on seat_count.
--
-- Seat numbering rules:
--   First:    rows 1+,  columns A/B         (2 seats/row)
--   Business: rows 10+, columns A/B/C/D     (4 seats/row)
--   Economy:  rows 20+, columns A/B/C/D/E/F (6 seats/row)
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_auto_generate_seats()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_start_row  INT;       -- Starting row number for this class
    v_cols       TEXT[];     -- Column letter array
    v_cols_count INT;        -- Number of columns per row
    v_row        INT;        -- Current row number
    v_col_idx    INT;        -- Current column index
    v_seat_label TEXT;       -- Generated seat label (e.g., '1A')
BEGIN
    -- Determine row start and column layout based on class name
    CASE NEW.class_name
        WHEN 'First' THEN
            v_start_row := 1;
            v_cols := ARRAY['A', 'B'];
        WHEN 'Business' THEN
            v_start_row := 10;
            v_cols := ARRAY['A', 'B', 'C', 'D'];
        WHEN 'Economy' THEN
            v_start_row := 20;
            v_cols := ARRAY['A', 'B', 'C', 'D', 'E', 'F'];
    END CASE;

    v_cols_count := array_length(v_cols, 1);

    -- Generate physical seat records
    FOR i IN 1..NEW.seat_count LOOP
        v_row     := v_start_row + ((i - 1) / v_cols_count);
        v_col_idx := ((i - 1) % v_cols_count) + 1;
        v_seat_label := v_row::TEXT || v_cols[v_col_idx];

        INSERT INTO public."SEAT_INVENTORY" (class_id, aircraft_id, seat_number)
        VALUES (NEW.class_id, NEW.aircraft_id, v_seat_label);
    END LOOP;

    RAISE NOTICE 'Auto-generated % seats for class "%" on aircraft %',
        NEW.seat_count, NEW.class_name, NEW.aircraft_id;

    RETURN NEW;
END;
$$;

-- Register trigger: fires AFTER INSERT on SEAT_CLASS
DROP TRIGGER IF EXISTS trg_auto_generate_seats ON public."SEAT_CLASS";
CREATE TRIGGER trg_auto_generate_seats
    AFTER INSERT ON public."SEAT_CLASS"
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_auto_generate_seats();


-- ============================================================
-- TRIGGER 2: Guard SEAT_CLASS updates (seat_count changes)
-- ============================================================
-- Integrity constraint: if seat_count is modified and there are
-- active bookings on any seat of that class, block the change
-- to protect data integrity. If no bookings exist, delete old
-- seats (new ones will be regenerated by the AFTER UPDATE trigger).
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_guard_seat_class_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_booked_count INT;
BEGIN
    -- Skip if seat_count has not changed
    IF NEW.seat_count = OLD.seat_count THEN
        RETURN NEW;
    END IF;

    -- Check if any seats of this class have active bookings
    SELECT COUNT(*) INTO v_booked_count
    FROM public."BOOKING" b
    JOIN public."SEAT_INVENTORY" si ON si.seat_id = b.seat_id
    WHERE si.class_id = OLD.class_id
      AND b.status = 'confirmed';

    IF v_booked_count > 0 THEN
        RAISE EXCEPTION
            'Cannot modify seat_count: % active booking(s) exist for class "%" on this aircraft.',
            v_booked_count, OLD.class_name;
    END IF;

    -- No active bookings — delete existing seats (AFTER trigger will regenerate)
    DELETE FROM public."SEAT_INVENTORY"
    WHERE class_id = OLD.class_id AND aircraft_id = OLD.aircraft_id;

    RETURN NEW;
END;
$$;

-- Register trigger: fires BEFORE UPDATE on SEAT_CLASS
DROP TRIGGER IF EXISTS trg_guard_seat_class_update ON public."SEAT_CLASS";
CREATE TRIGGER trg_guard_seat_class_update
    BEFORE UPDATE ON public."SEAT_CLASS"
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_guard_seat_class_update();

-- Regenerate seats after a valid seat_count update
-- (BEFORE trigger already deleted old seats; this one creates new ones)
CREATE OR REPLACE FUNCTION public.fn_regenerate_seats_after_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_start_row  INT;
    v_cols       TEXT[];
    v_cols_count INT;
    v_row        INT;
    v_col_idx    INT;
    v_seat_label TEXT;
BEGIN
    -- Skip if seat_count has not changed
    IF NEW.seat_count = OLD.seat_count THEN
        RETURN NEW;
    END IF;

    -- Determine layout (same logic as INSERT trigger)
    CASE NEW.class_name
        WHEN 'First' THEN
            v_start_row := 1;  v_cols := ARRAY['A', 'B'];
        WHEN 'Business' THEN
            v_start_row := 10; v_cols := ARRAY['A', 'B', 'C', 'D'];
        WHEN 'Economy' THEN
            v_start_row := 20; v_cols := ARRAY['A', 'B', 'C', 'D', 'E', 'F'];
    END CASE;

    v_cols_count := array_length(v_cols, 1);

    FOR i IN 1..NEW.seat_count LOOP
        v_row     := v_start_row + ((i - 1) / v_cols_count);
        v_col_idx := ((i - 1) % v_cols_count) + 1;
        v_seat_label := v_row::TEXT || v_cols[v_col_idx];

        INSERT INTO public."SEAT_INVENTORY" (class_id, aircraft_id, seat_number)
        VALUES (NEW.class_id, NEW.aircraft_id, v_seat_label);
    END LOOP;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_regenerate_seats_after_update ON public."SEAT_CLASS";
CREATE TRIGGER trg_regenerate_seats_after_update
    AFTER UPDATE ON public."SEAT_CLASS"
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_regenerate_seats_after_update();


-- ============================================================
-- TRIGGER 3: Validate booking integrity (BEFORE INSERT on BOOKING)
-- ============================================================
-- Integrity constraint enforced via trigger:
--   1) The seat must belong to the same aircraft as the flight
--   2) The flight must be in 'scheduled' status
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_validate_booking()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_flight_aircraft_id uuid;
    v_seat_aircraft_id   uuid;
    v_flight_status      varchar;
BEGIN
    -- Look up the flight's aircraft and status
    SELECT f.aircraft_id, f.status
      INTO v_flight_aircraft_id, v_flight_status
    FROM public."FLIGHT" f
    WHERE f.flight_id = NEW.flight_id;

    IF v_flight_aircraft_id IS NULL THEN
        RAISE EXCEPTION 'Flight % does not exist.', NEW.flight_id;
    END IF;

    -- Ensure the flight is bookable
    IF v_flight_status != 'scheduled' THEN
        RAISE EXCEPTION 'Cannot book: flight status is "%" (must be "scheduled").', v_flight_status;
    END IF;

    -- Look up the seat's aircraft
    SELECT si.aircraft_id
      INTO v_seat_aircraft_id
    FROM public."SEAT_INVENTORY" si
    WHERE si.seat_id = NEW.seat_id;

    IF v_seat_aircraft_id IS NULL THEN
        RAISE EXCEPTION 'Seat % does not exist.', NEW.seat_id;
    END IF;

    -- Ensure the seat belongs to the flight's aircraft
    IF v_seat_aircraft_id != v_flight_aircraft_id THEN
        RAISE EXCEPTION 'Seat does not belong to the aircraft assigned to this flight.';
    END IF;

    RETURN NEW;
END;
$$;

-- Register trigger: fires BEFORE INSERT on BOOKING
DROP TRIGGER IF EXISTS trg_validate_booking ON public."BOOKING";
CREATE TRIGGER trg_validate_booking
    BEFORE INSERT ON public."BOOKING"
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_validate_booking();


-- ############################################################
-- PART B. CORE BUSINESS FUNCTIONS (Stored Procedures)
-- ############################################################

-- ============================================================
-- 1) Generate Flights from Schedule
-- ============================================================
-- Creates individual flight records from recurring schedules
-- for a given date range. Uses the Schedule → Aircraft link.
-- ============================================================
CREATE OR REPLACE FUNCTION public.generate_flights(
    p_start_date date,
    p_end_date   date
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_count int := 0;
BEGIN
    IF p_start_date > p_end_date THEN
        RAISE EXCEPTION 'Invalid date range: start_date (%) > end_date (%)',
            p_start_date, p_end_date;
    END IF;

    INSERT INTO public."FLIGHT"(
        schedule_id, aircraft_id, flight_date, depart_time, arrival_time, status
    )
    SELECT
        fs.schedule_id,
        fs.aircraft_id,
        d.d_date::date,
        -- Departure datetime = date + scheduled time
        (d.d_date::timestamp + fs.depart_time)::timestamptz,
        -- Arrival datetime: if arrival_time <= depart_time, flight lands next day
        (
            CASE
                WHEN fs.arrival_time <= fs.depart_time
                THEN (d.d_date::timestamp + fs.arrival_time + interval '1 day')
                ELSE (d.d_date::timestamp + fs.arrival_time)
            END
        )::timestamptz,
        'scheduled'
    FROM public."FLIGHT_SCHEDULE" fs
    CROSS JOIN generate_series(p_start_date, p_end_date, interval '1 day') AS d(d_date)
    WHERE
        -- Only process dates within the schedule's validity range
        d.d_date::date BETWEEN fs.valid_from AND fs.valid_until
        -- Match operating days (supports Mon/Tue/... or 1/2/.../7 format)
        AND EXISTS (
            SELECT 1
            FROM unnest(string_to_array(
                replace(lower(fs.days_of_week), ' ', ''), ','
            )) AS t(tok)
            WHERE t.tok = lower(to_char(d.d_date::date, 'Dy'))
               OR t.tok = extract(isodow FROM d.d_date)::int::text
        )
        -- Skip dates that already have a generated flight
        AND NOT EXISTS (
            SELECT 1
            FROM public."FLIGHT" f
            WHERE f.schedule_id = fs.schedule_id
              AND f.flight_date = d.d_date::date
        );

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count || ' individual flights have been generated from the recurring schedules.';
END;
$$;


-- ============================================================
-- 2) Flight Search
-- ============================================================
-- Searches available flights by departure/arrival airport,
-- travel date, and optional seat class.
-- Returns stopover_list (comma-separated airport codes) via string_agg.
-- ============================================================
CREATE OR REPLACE FUNCTION public.search_flights(
    p_dep_iata    varchar,
    p_arr_iata    varchar,
    p_travel_date date,
    p_class_name  varchar DEFAULT NULL
)
RETURNS TABLE(
    flight_id       uuid,
    flight_number   varchar,
    airline_name    varchar,
    depart_time     timestamptz,
    arrival_time    timestamptz,
    class_name      varchar,
    price           numeric,
    available_seats bigint,
    stopover_list   text
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        v.flight_id,
        v.flight_number,
        v.airline_name,
        v.depart_time,
        v.arrival_time,
        v.class_name,
        v.price,
        v.available_seats,
        -- Build stopover list from STOPOVER table using string_agg
        (
            SELECT string_agg(s.airport_iata, ',' ORDER BY s.stop_order)
            FROM public."STOPOVER" s
            WHERE s.schedule_id = v.schedule_id
        ) AS stopover_list
    FROM public."FLIGHT_AVAILABILITY_VIEW" v
    WHERE v.depart_airport_iata = p_dep_iata
      AND v.dest_airport_iata  = p_arr_iata
      AND v.flight_date        = p_travel_date
      AND (p_class_name IS NULL OR v.class_name = p_class_name)
      AND v.available_seats > 0
    ORDER BY v.depart_time;
END;
$$;


-- ============================================================
-- 3) Create Booking (atomic transaction)
-- ============================================================
-- Atomically performs: seat reservation → payment → ticketing.
-- The trigger trg_validate_booking auto-validates seat/flight
-- integrity before the INSERT completes.
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_booking(
    p_customer_id uuid,
    p_flight_id   uuid,
    p_seat_id     uuid,
    p_amount      numeric
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
    v_booking_id uuid;
BEGIN
    -- Validate payment amount
    IF p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be > 0';
    END IF;

    -- Step 1: Create booking (trigger validates seat/flight integrity)
    BEGIN
        INSERT INTO public."BOOKING"(flight_id, customer_id, seat_id, status, price)
        VALUES (p_flight_id, p_customer_id, p_seat_id, 'confirmed', p_amount)
        RETURNING booking_id INTO v_booking_id;
    EXCEPTION WHEN unique_violation THEN
        RAISE EXCEPTION 'The selected seat is already occupied for this flight.';
    END;

    -- Step 2: Process payment
    INSERT INTO public."PAYMENT"(booking_id, amount, method, status)
    VALUES (v_booking_id, p_amount, 'credit_card', 'completed');

    -- Step 3: Issue ticket (ticket_no computed from booking_id in views/queries)
    INSERT INTO public."TICKET"(booking_id)
    VALUES (v_booking_id);

    RETURN v_booking_id;
END;
$$;


-- ============================================================
-- 4) Cancel Booking and Refund (atomic transaction)
-- ============================================================
-- Atomically performs: cancel booking → refund payment → delete ticket.
-- ============================================================
CREATE OR REPLACE FUNCTION public.cancel_booking(p_booking_id uuid)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_payment_id uuid;
    v_amount     numeric;
BEGIN
    -- Verify the booking exists and is active
    IF NOT EXISTS (
        SELECT 1 FROM public."BOOKING"
        WHERE booking_id = p_booking_id AND status = 'confirmed'
    ) THEN
        RAISE EXCEPTION 'Booking not found or already cancelled.';
    END IF;

    -- Lock and retrieve the associated payment (FOR UPDATE for concurrency)
    SELECT p.payment_id, p.amount
        INTO v_payment_id, v_amount
    FROM public."PAYMENT" p
    WHERE p.booking_id = p_booking_id
        AND p.status = 'completed'
    FOR UPDATE;

    IF v_payment_id IS NULL THEN
        RAISE EXCEPTION 'No completed payment found for booking %', p_booking_id;
    END IF;

    -- Delete ticket first (FK references BOOKING)
    DELETE FROM public."TICKET"
    WHERE booking_id = p_booking_id;

    -- Mark booking as cancelled
    UPDATE public."BOOKING"
    SET status = 'cancelled'
    WHERE booking_id = p_booking_id;

    -- Mark payment as refunded
    UPDATE public."PAYMENT"
    SET status = 'refunded'
    WHERE payment_id = v_payment_id;

    -- Create refund record
    INSERT INTO public."REFUND"(payment_id, amount, status, refunded_at)
    VALUES (v_payment_id, v_amount, 'completed', now());

    RETURN 'Booking ' || p_booking_id || ' has been successfully cancelled and refunded.';
END;
$$;


-- ============================================================
-- 5) Revenue Statistics Report
-- ============================================================
-- Aggregates revenue by flight, seat class, route, and time period.
-- Includes load factor (seat occupancy rate) per class.
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_revenue_report()
RETURNS TABLE (
    flight_id               uuid,
    flight_number           varchar,
    airline_name            varchar,
    route                   text,
    flight_date             date,
    revenue_month           timestamptz,
    revenue_quarter         timestamptz,
    class_name              varchar,
    total_revenue           numeric,
    class_revenue_pct       numeric,
    load_factor_percentage  numeric
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        v.flight_id,
        v.flight_number,
        v.airline_name,
        v.depart_airport_iata || ' -> ' || v.dest_airport_iata AS route,
        v.flight_date,
        v.revenue_month,
        v.revenue_quarter,
        v.class_name,
        v.revenue AS total_revenue,
        ROUND(
            100 * v.revenue
            / NULLIF(SUM(v.revenue) OVER (PARTITION BY v.flight_id, v.flight_date), 0),
            2
        ) AS class_revenue_pct,
        v.load_factor_pct AS load_factor_percentage
    FROM public."REVENUE_STATS_VIEW" v
    ORDER BY v.flight_date DESC, v.revenue DESC;
END;
$$;
