-- ============================================================
-- Airline Reservation System (AirBooking)
-- CSE 305 Term Project — Sample Seed Data
-- ============================================================
-- Execute AFTER: 01_schema.sql → 02_functions.sql → this file
-- SEAT_INVENTORY rows are auto-generated by the trigger on SEAT_CLASS INSERT.
--
-- Demo credentials:
--   Customer : alice@example.com  / 1234
--   Customer : bob@example.com    / 1234
--   Staff    : admin@airbooking.local / 1234
-- ============================================================


-- ============================================================
-- AIRPORTS (5)
-- ============================================================
INSERT INTO public."AIRPORT" (iata_code, name, country, city)
VALUES
  ('ICN', 'Incheon International Airport',        'South Korea',        'Incheon'),
  ('JFK', 'John F. Kennedy International Airport','United States',       'New York'),
  ('LHR', 'London Heathrow Airport',              'United Kingdom',      'London'),
  ('DXB', 'Dubai International Airport',          'United Arab Emirates','Dubai'),
  ('SIN', 'Singapore Changi Airport',             'Singapore',           'Singapore')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRLINES (3)
-- ============================================================
INSERT INTO public."AIRLINE" (iata_code, name, country)
VALUES
  ('KE', 'Korean Air',      'South Korea'),
  ('DL', 'Delta Air Lines', 'United States'),
  ('EK', 'Emirates',        'United Arab Emirates')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRCRAFT (3) — each owned by a specific airline
-- ============================================================
INSERT INTO public."AIRCRAFT" (airline_id, model)
SELECT airline_id, 'Boeing 777-300ER'
FROM public."AIRLINE" WHERE iata_code = 'KE'
ON CONFLICT DO NOTHING;

INSERT INTO public."AIRCRAFT" (airline_id, model)
SELECT airline_id, 'Airbus A350-900'
FROM public."AIRLINE" WHERE iata_code = 'DL'
ON CONFLICT DO NOTHING;

INSERT INTO public."AIRCRAFT" (airline_id, model)
SELECT airline_id, 'Airbus A380-800'
FROM public."AIRLINE" WHERE iata_code = 'EK'
ON CONFLICT DO NOTHING;


-- ============================================================
-- SEAT_CLASS (3 classes × 3 aircraft = 9 rows)
-- The trigger trg_auto_generate_seats will auto-populate
-- SEAT_INVENTORY for each row inserted here.
-- ============================================================

-- Korean Air Boeing 777-300ER
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    aircraft_id, 2, 1500.00 FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', aircraft_id, 2, 800.00  FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  aircraft_id, 6, 350.00  FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- Delta Airbus A350-900
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    aircraft_id, 2, 1800.00 FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'DL' AND ac.model = 'Airbus A350-900'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', aircraft_id, 2, 950.00  FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'DL' AND ac.model = 'Airbus A350-900'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  aircraft_id, 6, 400.00  FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'DL' AND ac.model = 'Airbus A350-900'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- Emirates Airbus A380-800
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    aircraft_id, 2, 2200.00 FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'EK' AND ac.model = 'Airbus A380-800'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', aircraft_id, 2, 1200.00 FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'EK' AND ac.model = 'Airbus A380-800'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  aircraft_id, 6, 500.00  FROM public."AIRCRAFT" ac JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id WHERE al.iata_code = 'EK' AND ac.model = 'Airbus A380-800'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- NOTE: At this point the trigger has auto-generated 30 physical seats
-- (10 per aircraft) in SEAT_INVENTORY.


-- ============================================================
-- FLIGHT_SCHEDULE (4 schedules)
-- ============================================================
INSERT INTO public."FLIGHT_SCHEDULE" (
  aircraft_id, depart_airport_iata, dest_airport_iata,
  flight_number, depart_time, arrival_time,
  days_of_week, valid_from, valid_until
)
SELECT
  ac.aircraft_id, 'ICN', 'JFK', 'KE001',
  '10:00', '10:00', 'Mon,Wed,Fri',
  '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
ON CONFLICT DO NOTHING;

INSERT INTO public."FLIGHT_SCHEDULE" (
  aircraft_id, depart_airport_iata, dest_airport_iata,
  flight_number, depart_time, arrival_time,
  days_of_week, valid_from, valid_until
)
SELECT
  ac.aircraft_id, 'JFK', 'LHR', 'DL100',
  '19:00', '07:00', 'Tue,Thu,Sat',
  '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'DL' AND ac.model = 'Airbus A350-900'
ON CONFLICT DO NOTHING;

INSERT INTO public."FLIGHT_SCHEDULE" (
  aircraft_id, depart_airport_iata, dest_airport_iata,
  flight_number, depart_time, arrival_time,
  days_of_week, valid_from, valid_until
)
SELECT
  ac.aircraft_id, 'ICN', 'LHR', 'EK350',
  '23:00', '17:00', 'Mon,Wed,Fri,Sun',
  '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'EK' AND ac.model = 'Airbus A380-800'
ON CONFLICT DO NOTHING;

INSERT INTO public."FLIGHT_SCHEDULE" (
  aircraft_id, depart_airport_iata, dest_airport_iata,
  flight_number, depart_time, arrival_time,
  days_of_week, valid_from, valid_until
)
SELECT
  ac.aircraft_id, 'SIN', 'ICN', 'KE621',
  '08:30', '16:30', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
  '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
ON CONFLICT DO NOTHING;


-- ============================================================
-- STOPOVER — EK350: ICN → DXB (layover 2h) → LHR
-- ============================================================
INSERT INTO public."STOPOVER" (
  schedule_id, airport_iata,
  arrival_time_offset, departure_time_offset, stop_order
)
SELECT
  schedule_id, 'DXB',
  interval '9 hours', interval '11 hours', 1
FROM public."FLIGHT_SCHEDULE"
WHERE flight_number = 'EK350'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;


-- ============================================================
-- CUSTOMERS (2)
-- ============================================================
INSERT INTO public."CUSTOMER" (email, password, name, passport)
VALUES
  ('alice@example.com', '1234', 'Alice Kim',     'M12345678'),
  ('bob@example.com',   '1234', 'Bob Johnson',   'N98765432')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- STAFF (1)
-- ============================================================
INSERT INTO public."STAFF" (email, password, name, role)
VALUES
  ('admin@airbooking.local', '1234', 'System Admin', 'admin')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- VERIFICATION QUERIES (optional)
-- ============================================================
-- SELECT * FROM public."AIRPORT";
-- SELECT * FROM public."AIRLINE";
-- SELECT a.model, al.name AS airline FROM public."AIRCRAFT" a JOIN public."AIRLINE" al ON al.airline_id = a.airline_id;
-- SELECT * FROM public."SEAT_CLASS";
-- SELECT COUNT(*) FROM public."SEAT_INVENTORY";   -- should be 30
-- SELECT * FROM public."FLIGHT_SCHEDULE";
-- SELECT * FROM public."STOPOVER";
-- SELECT email, name FROM public."CUSTOMER";
-- SELECT email, name, role FROM public."STAFF";
