-- ============================================================
-- Airline Reservation System (AirBooking)
-- CSE 305 Term Project — Sample Seed Data
-- ============================================================
-- Execute AFTER: 01_schema.sql → 02_functions.sql → this file
-- SEAT_INVENTORY rows are auto-generated by the trigger on SEAT_CLASS INSERT.
--
-- Data source: real-world IATA codes (openflights.org family).
-- Curated for the final demonstration:
--   ~40 airports, 14 airlines, 18 aircraft, 20 schedules
--   (6 of which are stopover routes — eligible for 15%/stop discount)
--
-- Demo credentials:
--   Customer : alice@example.com  / 1234
--   Customer : bob@example.com    / 1234
--   Customer : charlie@example.com / 1234
--   Staff    : admin@airbooking.local / 1234
-- ============================================================


-- ============================================================
-- AIRPORTS (40) — major international hubs across all continents
-- ============================================================
INSERT INTO public."AIRPORT" (iata_code, name, country, city)
VALUES
  -- East Asia
  ('ICN', 'Incheon International Airport',              'South Korea',          'Seoul'),
  ('GMP', 'Gimpo International Airport',                'South Korea',          'Seoul'),
  ('NRT', 'Narita International Airport',               'Japan',                'Tokyo'),
  ('HND', 'Haneda Airport',                             'Japan',                'Tokyo'),
  ('KIX', 'Kansai International Airport',               'Japan',                'Osaka'),
  ('PEK', 'Beijing Capital International Airport',      'China',                'Beijing'),
  ('PVG', 'Shanghai Pudong International Airport',      'China',                'Shanghai'),
  ('HKG', 'Hong Kong International Airport',            'Hong Kong',            'Hong Kong'),
  ('TPE', 'Taiwan Taoyuan International Airport',       'Taiwan',               'Taipei'),
  -- Southeast Asia / South Asia
  ('SIN', 'Singapore Changi Airport',                   'Singapore',            'Singapore'),
  ('BKK', 'Suvarnabhumi Airport',                       'Thailand',             'Bangkok'),
  ('KUL', 'Kuala Lumpur International Airport',         'Malaysia',             'Kuala Lumpur'),
  ('CGK', 'Soekarno-Hatta International Airport',       'Indonesia',            'Jakarta'),
  ('MNL', 'Ninoy Aquino International Airport',         'Philippines',          'Manila'),
  ('DEL', 'Indira Gandhi International Airport',        'India',                'New Delhi'),
  ('BOM', 'Chhatrapati Shivaji Maharaj Intl Airport',   'India',                'Mumbai'),
  -- Oceania
  ('SYD', 'Sydney Kingsford Smith Airport',             'Australia',            'Sydney'),
  ('MEL', 'Melbourne Airport',                          'Australia',            'Melbourne'),
  -- Middle East
  ('DXB', 'Dubai International Airport',                'United Arab Emirates', 'Dubai'),
  ('DOH', 'Hamad International Airport',                'Qatar',                'Doha'),
  ('IST', 'Istanbul Airport',                           'Turkey',               'Istanbul'),
  -- Europe
  ('LHR', 'London Heathrow Airport',                    'United Kingdom',       'London'),
  ('LGW', 'London Gatwick Airport',                     'United Kingdom',       'London'),
  ('CDG', 'Charles de Gaulle Airport',                  'France',               'Paris'),
  ('AMS', 'Amsterdam Schiphol Airport',                 'Netherlands',          'Amsterdam'),
  ('FRA', 'Frankfurt Airport',                          'Germany',              'Frankfurt'),
  ('MUC', 'Munich Airport',                             'Germany',              'Munich'),
  ('MAD', 'Adolfo Suarez Madrid-Barajas Airport',       'Spain',                'Madrid'),
  ('BCN', 'Barcelona-El Prat Airport',                  'Spain',                'Barcelona'),
  ('FCO', 'Leonardo da Vinci-Fiumicino Airport',        'Italy',                'Rome'),
  ('ZRH', 'Zurich Airport',                             'Switzerland',          'Zurich'),
  ('VIE', 'Vienna International Airport',               'Austria',              'Vienna'),
  -- North America
  ('JFK', 'John F. Kennedy International Airport',      'United States',        'New York'),
  ('LAX', 'Los Angeles International Airport',          'United States',        'Los Angeles'),
  ('ORD', 'O Hare International Airport',                'United States',        'Chicago'),
  ('ATL', 'Hartsfield-Jackson Atlanta Intl Airport',    'United States',        'Atlanta'),
  ('SFO', 'San Francisco International Airport',        'United States',        'San Francisco'),
  ('SEA', 'Seattle-Tacoma International Airport',       'United States',        'Seattle'),
  ('YYZ', 'Toronto Pearson International Airport',      'Canada',               'Toronto'),
  ('YVR', 'Vancouver International Airport',            'Canada',               'Vancouver')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRLINES (14) — major IATA-designated international carriers
-- ============================================================
INSERT INTO public."AIRLINE" (iata_code, name, country)
VALUES
  ('KE', 'Korean Air',            'South Korea'),
  ('OZ', 'Asiana Airlines',       'South Korea'),
  ('JL', 'Japan Airlines',        'Japan'),
  ('NH', 'All Nippon Airways',    'Japan'),
  ('CX', 'Cathay Pacific',        'Hong Kong'),
  ('SQ', 'Singapore Airlines',    'Singapore'),
  ('EK', 'Emirates',              'United Arab Emirates'),
  ('QR', 'Qatar Airways',         'Qatar'),
  ('LH', 'Lufthansa',             'Germany'),
  ('BA', 'British Airways',       'United Kingdom'),
  ('AF', 'Air France',            'France'),
  ('DL', 'Delta Air Lines',       'United States'),
  ('AA', 'American Airlines',     'United States'),
  ('UA', 'United Airlines',       'United States')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRCRAFT (18) — real fleet assignments
-- ============================================================
INSERT INTO public."AIRCRAFT" (airline_id, model)
SELECT airline_id, model FROM (VALUES
  ('KE', 'Boeing 777-300ER'),
  ('KE', 'Airbus A380-800'),
  ('OZ', 'Airbus A350-900'),
  ('JL', 'Boeing 787-9'),
  ('NH', 'Boeing 787-9'),
  ('CX', 'Boeing 777-300ER'),
  ('SQ', 'Airbus A350-900'),
  ('SQ', 'Airbus A380-800'),
  ('EK', 'Airbus A380-800'),
  ('EK', 'Boeing 777-300ER'),
  ('QR', 'Boeing 777-300ER'),
  ('LH', 'Boeing 747-8'),
  ('LH', 'Airbus A350-900'),
  ('BA', 'Boeing 777-300ER'),
  ('AF', 'Boeing 777-300ER'),
  ('DL', 'Airbus A350-900'),
  ('AA', 'Boeing 777-300ER'),
  ('UA', 'Boeing 787-10')
) AS v(iata, model)
JOIN public."AIRLINE" al ON al.iata_code = v.iata
ON CONFLICT DO NOTHING;


-- ============================================================
-- SEAT_CLASS — 3 classes per aircraft (54 rows total)
-- The trigger trg_auto_generate_seats will auto-populate
-- SEAT_INVENTORY for each row inserted here.
-- Seat counts vary by aircraft type:
--   B787-9 / B787-10 / A350: First 2, Business 4, Economy 18
--   B777-300ER:              First 2, Business 6, Economy 24
--   A380-800 / B747-8:       First 4, Business 8, Economy 30
-- ============================================================

-- For each aircraft, insert three seat classes using a CTE-like approach.
-- Pricing reflects rough real-world fare bands per class per aircraft type.

-- A380-800 / 747-8 (largest aircraft → highest capacity, premium pricing)
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    ac.aircraft_id, 4,  2200.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A380-800', 'Boeing 747-8')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', ac.aircraft_id, 8,  1200.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A380-800', 'Boeing 747-8')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  ac.aircraft_id, 30, 500.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A380-800', 'Boeing 747-8')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- B777-300ER (large wide-body)
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    ac.aircraft_id, 2,  1800.00
FROM public."AIRCRAFT" ac
WHERE ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', ac.aircraft_id, 6,  1000.00
FROM public."AIRCRAFT" ac
WHERE ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  ac.aircraft_id, 24, 450.00
FROM public."AIRCRAFT" ac
WHERE ac.model = 'Boeing 777-300ER'
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- A350-900 / B787-9 / B787-10 (modern wide-body, mid-size)
INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'First',    ac.aircraft_id, 2,  1600.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A350-900', 'Boeing 787-9', 'Boeing 787-10')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Business', ac.aircraft_id, 4,  900.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A350-900', 'Boeing 787-9', 'Boeing 787-10')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

INSERT INTO public."SEAT_CLASS" (class_name, aircraft_id, seat_count, price)
SELECT 'Economy',  ac.aircraft_id, 18, 400.00
FROM public."AIRCRAFT" ac
WHERE ac.model IN ('Airbus A350-900', 'Boeing 787-9', 'Boeing 787-10')
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- NOTE: At this point the trigger has auto-generated all
-- physical seats across the 18 aircraft.


-- ============================================================
-- FLIGHT_SCHEDULE (20 schedules — real intercontinental routes)
-- 14 direct + 6 stopover.
-- Helper macro pattern: pick first aircraft matching airline+model.
-- ============================================================

-- ── DIRECT ROUTES (14) ──────────────────────────────────────

-- KE001 — Korean Air ICN → JFK (Mon/Wed/Fri)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'ICN', 'JFK', 'KE001',
  '10:00', '10:30', 'Mon,Wed,Fri', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'KE' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- KE017 — Korean Air ICN → LAX (Tue/Thu/Sat)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'ICN', 'LAX', 'KE017',
  '20:00', '14:00', 'Tue,Thu,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'KE' AND ac.model = 'Airbus A380-800'
LIMIT 1
ON CONFLICT DO NOTHING;

-- OZ102 — Asiana ICN → NRT (daily)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'ICN', 'NRT', 'OZ102',
  '09:00', '11:30', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'OZ' AND ac.model = 'Airbus A350-900'
LIMIT 1
ON CONFLICT DO NOTHING;

-- JL043 — JAL HND → JFK (Tue/Thu/Sun)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'HND', 'JFK', 'JL043',
  '11:00', '11:00', 'Tue,Thu,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'JL' AND ac.model = 'Boeing 787-9'
LIMIT 1
ON CONFLICT DO NOTHING;

-- NH106 — ANA HND → LHR (Mon/Wed/Fri/Sun)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'HND', 'LHR', 'NH106',
  '11:30', '16:30', 'Mon,Wed,Fri,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'NH' AND ac.model = 'Boeing 787-9'
LIMIT 1
ON CONFLICT DO NOTHING;

-- CX880 — Cathay HKG → LAX (Mon/Wed/Fri)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'HKG', 'LAX', 'CX880',
  '00:15', '21:30', 'Mon,Wed,Fri', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'CX' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- SQ322 — Singapore Airlines SIN → LHR (Tue/Thu/Sat)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'SIN', 'LHR', 'SQ322',
  '23:55', '06:00', 'Tue,Thu,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'SQ' AND ac.model = 'Airbus A350-900'
LIMIT 1
ON CONFLICT DO NOTHING;

-- EK202 — Emirates DXB → JFK (daily)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'DXB', 'JFK', 'EK202',
  '08:30', '14:15', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'EK' AND ac.model = 'Airbus A380-800'
LIMIT 1
ON CONFLICT DO NOTHING;

-- QR701 — Qatar DOH → JFK (Mon/Thu/Fri/Sun)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'DOH', 'JFK', 'QR701',
  '01:55', '07:45', 'Mon,Thu,Fri,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'QR' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- LH400 — Lufthansa FRA → JFK (daily)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'FRA', 'JFK', 'LH400',
  '10:00', '13:00', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'LH' AND ac.model = 'Boeing 747-8'
LIMIT 1
ON CONFLICT DO NOTHING;

-- BA15 — British Airways LHR → SIN (Tue/Wed/Fri/Sat)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'LHR', 'SIN', 'BA15',
  '21:30', '17:35', 'Tue,Wed,Fri,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'BA' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- AF272 — Air France CDG → ICN (Mon/Wed/Sat)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'CDG', 'ICN', 'AF272',
  '19:50', '14:30', 'Mon,Wed,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'AF' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- DL159 — Delta ATL → ICN (daily)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'ATL', 'ICN', 'DL159',
  '11:25', '17:10', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'DL' AND ac.model = 'Airbus A350-900'
LIMIT 1
ON CONFLICT DO NOTHING;

-- UA853 — United SFO → NRT (daily)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'SFO', 'NRT', 'UA853',
  '11:30', '15:15', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'UA' AND ac.model = 'Boeing 787-10'
LIMIT 1
ON CONFLICT DO NOTHING;


-- ── STOPOVER ROUTES (6) — eligible for 15%/stop discount ────

-- EK350 — Emirates ICN → DXB → LHR (1 stop)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'ICN', 'LHR', 'EK350',
  '23:55', '17:00', 'Mon,Wed,Fri,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'EK' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- QR858 — Qatar SIN → DOH → CDG (1 stop)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'SIN', 'CDG', 'QR858',
  '21:15', '13:30', 'Tue,Thu,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'QR' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- LH716 — Lufthansa HND → FRA → MAD (1 stop)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'HND', 'MAD', 'LH716',
  '21:45', '16:00', 'Mon,Wed,Fri', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'LH' AND ac.model = 'Airbus A350-900'
LIMIT 1
ON CONFLICT DO NOTHING;

-- SQ12 — Singapore Airlines SIN → NRT → LAX (1 stop)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'SIN', 'LAX', 'SQ12',
  '07:45', '13:00', 'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'SQ' AND ac.model = 'Airbus A380-800'
LIMIT 1
ON CONFLICT DO NOTHING;

-- BA284 — British Airways LHR → SEA → YVR (2 stops) -- via SEA + intermediate SFO
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'LHR', 'YVR', 'BA284',
  '15:00', '11:30', 'Tue,Thu,Sat', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'BA' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;

-- AF7755 — Air France BOM → CDG → JFK (1 stop, code-share style)
INSERT INTO public."FLIGHT_SCHEDULE"
  (aircraft_id, depart_airport_iata, dest_airport_iata,
   flight_number, depart_time, arrival_time, days_of_week, valid_from, valid_until)
SELECT ac.aircraft_id, 'BOM', 'JFK', 'AF7755',
  '02:20', '15:00', 'Mon,Wed,Fri,Sun', '2026-05-01', '2026-08-31'
FROM public."AIRCRAFT" ac
JOIN public."AIRLINE" al ON al.airline_id = ac.airline_id
WHERE al.iata_code = 'AF' AND ac.model = 'Boeing 777-300ER'
LIMIT 1
ON CONFLICT DO NOTHING;


-- ============================================================
-- STOPOVER (7 rows: 5 single-stop schedules + 1 two-stop schedule)
-- ============================================================

-- EK350: DXB stop, arrives +10h, departs +12h
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'DXB', interval '10 hours', interval '12 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'EK350'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

-- QR858: DOH stop
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'DOH', interval '7 hours', interval '9 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'QR858'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

-- LH716: FRA stop
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'FRA', interval '13 hours', interval '15 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'LH716'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

-- SQ12: NRT stop
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'NRT', interval '6 hours', interval '8 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'SQ12'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

-- BA284: SFO + SEA stops (2 stops)
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'SFO', interval '10 hours', interval '12 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'BA284'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'SEA', interval '14 hours', interval '16 hours', 2
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'BA284'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;

-- AF7755: CDG stop
INSERT INTO public."STOPOVER" (schedule_id, airport_iata, arrival_time_offset, departure_time_offset, stop_order)
SELECT schedule_id, 'CDG', interval '9 hours', interval '11 hours', 1
FROM public."FLIGHT_SCHEDULE" WHERE flight_number = 'AF7755'
ON CONFLICT (schedule_id, stop_order) DO NOTHING;


-- ============================================================
-- CUSTOMERS (3)
-- ============================================================
INSERT INTO public."CUSTOMER" (email, password, name, passport)
VALUES
  ('alice@example.com',   '1234', 'Alice Kim',     'M12345678'),
  ('bob@example.com',     '1234', 'Bob Johnson',   'N98765432'),
  ('charlie@example.com', '1234', 'Charlie Lee',   'P55512345')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- STAFF (1)
-- ============================================================
INSERT INTO public."STAFF" (email, password, name, role)
VALUES
  ('admin@airbooking.local', '1234', 'System Admin', 'admin')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- VERIFICATION QUERIES (optional)
-- ============================================================
-- SELECT COUNT(*) FROM public."AIRPORT";          -- 40
-- SELECT COUNT(*) FROM public."AIRLINE";          -- 14
-- SELECT COUNT(*) FROM public."AIRCRAFT";         -- 18
-- SELECT COUNT(*) FROM public."SEAT_CLASS";       -- 54
-- SELECT COUNT(*) FROM public."SEAT_INVENTORY";   -- ~530 (trigger-generated)
-- SELECT COUNT(*) FROM public."FLIGHT_SCHEDULE";  -- 20
-- SELECT COUNT(*) FROM public."STOPOVER";         -- 7
-- SELECT email, name FROM public."CUSTOMER";
-- SELECT email, name, role FROM public."STAFF";
