-- ============================================================
-- Airline Reservation System (AirBooking)
-- CSE 305 Term Project — Sample Seed Data
-- ============================================================
-- Execute AFTER: 01_schema.sql → 02_functions.sql → this file
-- SEAT_INVENTORY rows are auto-generated by the trigger on SEAT_CLASS INSERT.
--
-- Readable UUID Scheme:
--   Airports  → ...0101 ~ 0105
--   Airlines  → ...0201 ~ 0203
--   Aircraft  → ...0301 ~ 0303
--   SeatClass → ...0401 ~ 0409
--   Schedules → ...0501 ~ 0504
--   Customers → ...0601 ~ 0602
--   Staff     → ...0701
--   Stopovers → ...0801
-- ============================================================


-- ============================================================
-- AIRPORTS (5)
-- ============================================================
INSERT INTO public."AIRPORT" (airport_id, iata_code, name, country, city)
VALUES
  ('00000000-0000-0000-0000-000000000101'::uuid, 'ICN',
   'Incheon International Airport', 'South Korea', 'Incheon'),
  ('00000000-0000-0000-0000-000000000102'::uuid, 'JFK',
   'John F. Kennedy International Airport', 'United States', 'New York'),
  ('00000000-0000-0000-0000-000000000103'::uuid, 'LHR',
   'London Heathrow Airport', 'United Kingdom', 'London'),
  ('00000000-0000-0000-0000-000000000104'::uuid, 'DXB',
   'Dubai International Airport', 'United Arab Emirates', 'Dubai'),
  ('00000000-0000-0000-0000-000000000105'::uuid, 'SIN',
   'Singapore Changi Airport', 'Singapore', 'Singapore')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRLINES (3)
-- ============================================================
INSERT INTO public."AIRLINE" (airline_id, iata_code, name, country)
VALUES
  ('00000000-0000-0000-0000-000000000201'::uuid, 'KE', 'Korean Air',  'South Korea'),
  ('00000000-0000-0000-0000-000000000202'::uuid, 'DL', 'Delta Air Lines', 'United States'),
  ('00000000-0000-0000-0000-000000000203'::uuid, 'EK', 'Emirates',    'United Arab Emirates')
ON CONFLICT (iata_code) DO NOTHING;


-- ============================================================
-- AIRCRAFT (3) — each owned by a specific airline
-- ============================================================
INSERT INTO public."AIRCRAFT" (aircraft_id, airline_id, model)
VALUES
  -- Korean Air's Boeing 777-300ER
  ('00000000-0000-0000-0000-000000000301'::uuid,
   '00000000-0000-0000-0000-000000000201'::uuid, 'Boeing 777-300ER'),
  -- Delta's Airbus A350-900
  ('00000000-0000-0000-0000-000000000302'::uuid,
   '00000000-0000-0000-0000-000000000202'::uuid, 'Airbus A350-900'),
  -- Emirates' Airbus A380-800
  ('00000000-0000-0000-0000-000000000303'::uuid,
   '00000000-0000-0000-0000-000000000203'::uuid, 'Airbus A380-800')
ON CONFLICT (aircraft_id) DO NOTHING;


-- ============================================================
-- SEAT_CLASS (3 classes × 3 aircraft = 9 rows)
-- The trigger trg_auto_generate_seats will auto-populate
-- SEAT_INVENTORY for each row inserted here.
--
-- Per aircraft totals:
--   First(2) + Business(2) + Economy(6) = 10 seats  (≥ 8 requirement)
-- ============================================================

-- Korean Air Boeing 777-300ER
INSERT INTO public."SEAT_CLASS" (class_id, class_name, aircraft_id, seat_count, price)
VALUES
  ('00000000-0000-0000-0000-000000000401'::uuid, 'First',
   '00000000-0000-0000-0000-000000000301'::uuid, 2, 1500.00),
  ('00000000-0000-0000-0000-000000000402'::uuid, 'Business',
   '00000000-0000-0000-0000-000000000301'::uuid, 2, 800.00),
  ('00000000-0000-0000-0000-000000000403'::uuid, 'Economy',
   '00000000-0000-0000-0000-000000000301'::uuid, 6, 350.00)
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- Delta Airbus A350-900
INSERT INTO public."SEAT_CLASS" (class_id, class_name, aircraft_id, seat_count, price)
VALUES
  ('00000000-0000-0000-0000-000000000404'::uuid, 'First',
   '00000000-0000-0000-0000-000000000302'::uuid, 2, 1800.00),
  ('00000000-0000-0000-0000-000000000405'::uuid, 'Business',
   '00000000-0000-0000-0000-000000000302'::uuid, 2, 950.00),
  ('00000000-0000-0000-0000-000000000406'::uuid, 'Economy',
   '00000000-0000-0000-0000-000000000302'::uuid, 6, 400.00)
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- Emirates Airbus A380-800
INSERT INTO public."SEAT_CLASS" (class_id, class_name, aircraft_id, seat_count, price)
VALUES
  ('00000000-0000-0000-0000-000000000407'::uuid, 'First',
   '00000000-0000-0000-0000-000000000303'::uuid, 2, 2200.00),
  ('00000000-0000-0000-0000-000000000408'::uuid, 'Business',
   '00000000-0000-0000-0000-000000000303'::uuid, 2, 1200.00),
  ('00000000-0000-0000-0000-000000000409'::uuid, 'Economy',
   '00000000-0000-0000-0000-000000000303'::uuid, 6, 500.00)
ON CONFLICT (aircraft_id, class_name) DO NOTHING;

-- NOTE: At this point, the trigger has auto-generated 30 physical seats
-- (10 per aircraft) in SEAT_INVENTORY. No manual insert needed!


-- ============================================================
-- FLIGHT_SCHEDULE (4 schedules)
-- Airline is derived via: Schedule → Aircraft → Airline
-- ============================================================
INSERT INTO public."FLIGHT_SCHEDULE" (
  schedule_id, aircraft_id,
  depart_airport_iata, dest_airport_iata,
  flight_number, depart_time, arrival_time,
  days_of_week, valid_from, valid_until
)
VALUES
  -- KE001: ICN → JFK (Korean Air, Mon/Wed/Fri, ~14h flight)
  ('00000000-0000-0000-0000-000000000501'::uuid,
   '00000000-0000-0000-0000-000000000301'::uuid,
   'ICN', 'JFK', 'KE001', '10:00', '10:00',
   'Mon,Wed,Fri', '2026-05-01', '2026-08-31'),

  -- DL100: JFK → LHR (Delta, Tue/Thu/Sat, ~7h flight)
  ('00000000-0000-0000-0000-000000000502'::uuid,
   '00000000-0000-0000-0000-000000000302'::uuid,
   'JFK', 'LHR', 'DL100', '19:00', '07:00',
   'Tue,Thu,Sat', '2026-05-01', '2026-08-31'),

  -- EK350: ICN → LHR via DXB (Emirates, Mon/Wed/Fri/Sun, ~18h total)
  ('00000000-0000-0000-0000-000000000503'::uuid,
   '00000000-0000-0000-0000-000000000303'::uuid,
   'ICN', 'LHR', 'EK350', '23:00', '17:00',
   'Mon,Wed,Fri,Sun', '2026-05-01', '2026-08-31'),

  -- KE621: SIN → ICN (Korean Air, daily, ~6h flight)
  ('00000000-0000-0000-0000-000000000504'::uuid,
   '00000000-0000-0000-0000-000000000301'::uuid,
   'SIN', 'ICN', 'KE621', '08:30', '16:30',
   'Mon,Tue,Wed,Thu,Fri,Sat,Sun', '2026-05-01', '2026-08-31')
ON CONFLICT (schedule_id) DO NOTHING;


-- ============================================================
-- STOPOVER (ICN → DXB → LHR route)
-- EK350 has a layover at DXB:
--   Depart ICN at 23:00
--   Arrive DXB after ~9h (+9:00), depart DXB after ~11h (+11:00)
--   Arrive LHR at 17:00 next day (+18:00 total)
-- ============================================================
INSERT INTO public."STOPOVER" (
  stopover_id, schedule_id, airport_iata,
  arrival_time_offset, departure_time_offset, stop_order
)
VALUES
  ('00000000-0000-0000-0000-000000000801'::uuid,
   '00000000-0000-0000-0000-000000000503'::uuid,
   'DXB',
   interval '9 hours',      -- arrives at DXB 9h after departure from ICN
   interval '11 hours',     -- departs DXB 11h after departure from ICN (2h layover)
   1)
ON CONFLICT (schedule_id, stop_order) DO NOTHING;


-- ============================================================
-- CUSTOMERS (2)
-- ============================================================
INSERT INTO public."CUSTOMER" (customer_id, email, password, name, passport)
VALUES
  ('00000000-0000-0000-0000-000000000601'::uuid,
   'alice@example.com',
   '$2b$12$LJ3m5Fqz8XZWJ0pK9vjXKeQR5d6HBXLP9mN2Q8sS7w0sW9mH5GzK',
   'Alice Kim', 'M12345678'),
  ('00000000-0000-0000-0000-000000000602'::uuid,
   'bob@example.com',
   '$2b$12$LJ3m5Fqz8XZWJ0pK9vjXKeQR5d6HBXLP9mN2Q8sS7w0sW9mH5GzK',
   'Bob Johnson', 'N98765432')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- STAFF (1)
-- ============================================================
INSERT INTO public."STAFF" (staff_id, email, password, name, role)
VALUES
  ('00000000-0000-0000-0000-000000000701'::uuid,
   'admin@airbooking.local',
   '$2b$12$LJ3m5Fqz8XZWJ0pK9vjXKeQR5d6HBXLP9mN2Q8sS7w0sW9mH5GzK',
   'System Admin', 'admin')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- VERIFICATION QUERIES (optional — run to confirm seed data)
-- ============================================================
-- SELECT * FROM public."AIRPORT";
-- SELECT * FROM public."AIRLINE";
-- SELECT a.aircraft_id, al.name AS airline, a.model
--   FROM public."AIRCRAFT" a JOIN public."AIRLINE" al ON al.airline_id = a.airline_id;
-- SELECT * FROM public."SEAT_CLASS";
-- SELECT * FROM public."SEAT_INVENTORY" ORDER BY aircraft_id, seat_number;
-- SELECT * FROM public."FLIGHT_SCHEDULE";
-- SELECT * FROM public."STOPOVER";
-- SELECT * FROM public."CUSTOMER";
-- SELECT * FROM public."STAFF";
